### ISSUE TITLE
/usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by satouriko** [kokororin/kaomojify#1]
The files from npm that are using CRLF instead of LF, will cause this issue while executed on Unix-Like systems.

**Comment by kokororin** [comment]
![untitled](https://user-images.githubusercontent.com/10093992/36338638-e277cd7c-13ef-11e8-90b5-7de7b3a36ed5.gif)
Test in macOS and Ubuntu just now, it works.
You can create a Pull Request.

**Comment by satouriko** [comment]
Ah...I was mistaken. It is yarn, not npm
npm does work well

**Comment by kokororin** [comment]
Fixed in 0.2.3
